### ISSUE TITLE
Custom ExpiryPolicy Requirement?

### ISSUE THREAD

**Issue by gregrluck** [jsr107/jsr107spec#126]
## From Spec Leads + Terracotta

How many people really want to use a custom expiry policy instead of just using TTI/TTL.  Forcing implementations to support a custom policy seems to be extreme overkill.  Obviously you can just revert to some crappy non-performant implementation when someone uses a custom policy - but the real danger to me is that over-zealous customers will use a custom policy because they can, and not because they need it.  Then we get stuck with the fallout from their crappy decision - better to close that door now rather than having to close it N times - where N is the number of idiotic users.

**Comment by Scuilion** [comment]
To clarify, it appears that Custom ExpiryPolicy was favored but was never implemented?

**Comment by cruftex** [comment]
@Scuilion 
It was included in the standard, e.g. see the JSR JavaDoc:
https://cache2k.org/docs/jcache/1.1.0/apidocs/cache-api/javax/cache/expiry/ExpiryPolicy.html
