### ISSUE TITLE
Wrong reference to put in CacheRemove/CacheRemoveAll

### ISSUE THREAD

**Issue by snicoll** [jsr107/jsr107spec#294]
The Javadoc of `@CacheRemove#afterInvocation` refers to the put operation while it should probably be the remove operation. Excerpt:
_If true and the annotated method throws an exception the put will not be executed._

`CacheRemoveAll` is affected as well.

Besides, this statement does not take the `evictFor` and `noEvictFor` parameters.

**Comment by gregrluck** [comment]
Fixed.
