### ISSUE TITLE
What is actual license for JSR 107 API?

### ISSUE THREAD

**Issue by netudima** [jsr107/jsr107spec#304]
Could you please clarify what is the current license for JSR 107 API?
From one side the published artifact and sources uses https://github.com/jsr107/jsr107spec/blob/master/LICENSE.txt, which is custom one. 
From another side https://jcp.org/en/jsr/detail?id=107 page mentions CDDL 1.1 and GPLv2 with Classpath Exception.
Source files do not contain an explicit license header.

**Comment by gregrluck** [comment]
The spec license is actually wrong. It is appropriate for an early draft but not for final. We will:

a) get Oracle legal to give us the correct wording, similar to your example for a final spec
b) copy that into the LICENSE.txt in the jar

There is a second issue that the spec doc mentions CDDL and Apache. We need to work that into the spec as well.

**Comment by keilw** [comment]
the TCK also mentions Apache despite other license(s) seemingly apply there;-) See https://github.com/jsr107/jsr107tck/issues/80

**Comment by gregrluck** [comment]
I checked https://jcp.org/en/jsr/detail?id=107 page

For the spec it mentions the specification license which is correct. So no issue. 

CDDL talk about the RI and TCK. So far we have only released those as Apache 2.

**Comment by keilw** [comment]
The artifact is called "spec" which is a bit misleading. Similar to JSR 363 it seems the actual Spec is in Google Docs. So https://github.com/jsr107/jsr107spec/blob/master/LICENSE.txt is in a repository it may not fully apply to. At least that's exactly what Eclipse (or OGC) were concerned about in the case of the JSR 363 API. Following another Oracle-lead JSR 375 (https://github.com/javaee-security-spec/spec-api) it mentions the RI/TCK licenses in the LICENSE.* file (whild the actual spec document contains the Spec License) Unless Co-Spec Lead Oracle had an issue, it might make life easier with most OSS communities. At least we now stick to the same policy as pretty much every Oracle lead JSR.

**Comment by netmackan** [comment]
Still very confusing for an open source project trying to determine if the API can even be used... 
Is cache-api-1.0.0.jar Apache 2 licensed?

**Comment by keilw** [comment]
You certainly scratch an itch with that question ;-)
