### ISSUE TITLE
Cache* annotations should also have `@InterceptorBinding` annotation

### ISSUE THREAD

**Issue by slaskawi** [jsr107/jsr107spec#305]
Annotations scanned by CDI interceptors should contain also `@InterceptorBinding` annotation.

According to CDI 1.0 spec [1] an interceptor should contain an `@InterceptorBinding` annotation or non-portable behavior may occur. Please note that Cache* annotations (e.g. CacheResult) contain `@Nonbinding` but there is no `@InterceptorBinding`. According to StackOverflow question [2] it is very hard to properly implement an interceptor in these circumstances. 

[1] https://docs.jboss.org/cdi/spec/1.0/html/interceptors.html
[2] http://stackoverflow.com/questions/16532984/cdi-how-to-apply-interceptor-to-library-third-party-code

**Comment by gregrluck** [comment]
This would add an EE dependency to JCache which we dot want as we only have an SE dependency. Furthermore CDI is only one Annotation Processor targeted and this is specific to CDI.
