### ISSUE TITLE
Wrong version in Spec License

### ISSUE THREAD

**Issue by keilw** [jsr107/jsr107spec#308]
LICENSE.txt says something like
JSR-000107 JCACHE 2.9 Public Review - Updated Specification 
 
 
 ORACLE AND GREG LUCK ARE WILLING TO LICENSE THIS SPECIFICATION TO YOU ONLY UPON THE CONDITION THAT YOU ACCEPT ALL OF THE TERMS CONTAINED IN THIS LICENSE AGREEMENT ("AGREEMENT"). PLEASE READ THE TERMS AND CONDITIONS OF THIS AGREEMENT CAREFULLY. BY DOWNLOADING THIS SPECIFICATION, YOU ACCEPT THE TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU ARE NOT WILLING TO BE BOUND BY THEM, SELECT THE "DECLINE" BUTTON AT THE BOTTOM OF THIS PAGE AND THE DOWNLOADING PROCESS WILL NOT CONTINUE. 
 Specification: JSR-000107 Java(tm) Temporary Caching API Specification ("Specification") 
 Version: 2.9 
 Status: Public Review 
 Release: 8 August 2013 

The version makes no sense, JSR-107 was published as Version 1.0, a potential MR would raise this to 1.1, but not 2.9. Please correct.

**Comment by gregrluck** [comment]
Werner

2.9 is the JCP version.

We should fix that and add the version number which as you say was 1.0 and is proposed to be 1.1.

Note that the status is also wrong. `it says Public Review but should say Final.

Regards

Greg Luck

web: http://gregluck.com <http://gregluck.com/>
skype: gregrluck
yahoo: gregrluck
mobile: +61 408 061 622

**Comment by keilw** [comment]
OK, that explains where the 2.9 comes from, but in standard Spec Licenses like this template:
https://jcp.org/aboutJava/communityprocess/speclead/final-license.txt
Version:  <____>
refers to the JSR not the JCP version.

Regards,
Werner

**Comment by gregrluck** [comment]
Ok, changed to 1.1 for the new 1.1. spec. See https://docs.google.com/document/d/14BvLUyv5U3zhsbIGwA4hkLfFieBkaCPfaHazh_yQGSY/edit?usp=sharing
