### ISSUE TITLE
Make EntryProcessor Serializable?

### ISSUE THREAD

**Issue by dsetrakyan** [jsr107/jsr107spec#309]
Hi,

Is there any way to make EntryProcessor extend Serializable? Otherwise it is impossible to use Java8 lambda notation for it when working with distributed caches.

Thanks,
-Dmitriy

**Comment by brianoliver** [comment]
Hi Dmitriy,

I don't believe making EntryProcessor extend Serializable is a requirement for EntryProcessors to be used with Java 8 across servers.

While your solution *may* need something serializable, it's not a requirement for the specification, but rather a *possible* requirement for an implementation.

For example:   The next release of Oracle Coherence supports the use of Java 8 lambdas and "distributed" streams across a cluster without developers being required to implement Serializable, or without making changes to public interfaces.

Furthermore (and as discussed with the Java Language team), making EntryProcessors Serializable introduces certain inefficiencies (additional code/memory footprint) when Java generates code for lambda expressions.   This would adversely impact non-distributed Caches, which is one of the reasons why EntryProcessors are not serializable in the first place.

The JCache Specification was carefully designed to ensure that things like Serialization aren't unnecessarily forced upon developers or implementors of the specification.   

Given our experience implementing lambda support with Oracle Coherence, I believe the Java language provides enough facilities to allow you to achieve what you require, without us changing the specification.

Please note that the Java Language team discussed the serializablility of lambda expressions (amongst many other Java 8 features) at great length.   I believe the current design of Java and the JCache specification are valid and consistent.

-- Brian

**Comment by dsetrakyan** [comment]
I think you were a little too quick to close this ticket (I was hoping to have some room for discussion). I honestly don't see how Serializable EntryProcessor would adversely impact non-distributed caches, especially since EntryProcessor is not stored in cache at all.

All I wanted to make sure is that code like this can execute in a distributed cluster. I think we can all agree that community and users would largely benefit from it:

    for (int i = 0; i < 10; i++)
		cache.invoke("mykey", (entry, args) -> {
		  Integer val = entry.getValue();

		  entry.setValue(val == null ? 1 : val + 1);

		  return null;
		});

**Comment by brianoliver** [comment]
This is a very similar to the arguments proposed to the Java Language Team about Lambda Serialization.   On one hand examples like those above look to be "no cost" and "completely safe" but that is not true at all at the language / byte-code level, especially when serialization is taken into account.  

ASIDE: I closed this issue as it's not really about the JCache specification.  It's about the application of a Java 8 language feature to the JCache specification (which is actually designed for Java 6).

Perhaps you might like to ask yourself the following question:  Why aren't all (functional) interfaces in the Java Language that could be implemented using lambdas made (forced) to now extend Serializable?    This may seem extreme proposition, but that is essentially what your asking us to do to the JCache specification.

Ultimately to really engage in a deep discussion about this topic, you need to have an in depth understanding of what is happening at the byte-code level and importantly the "stability of serialization", especially with respect to a distributed system.   Brian Goetz touches on the subject here with respect to the design of the feature:

http://mail.openjdk.java.net/pipermail/lambda-spec-experts/2013-July/000316.html

Apart from byte-code level efficiencies / inefficiencies, in reality the above code sample makes implicit assumptions about the "identity" and "stability" of  lambda expressions once compiled in an application.  It also makes deployment and runtime assumptions with respect to the class-loading, availability and versioning of classes for an application across a cluster, things that are naturally outside the scope of the JCache specification.    More specifically, the JCache specification makes it very clear that these are "implementation concerns", not semantics to be enforced onto providers. The specification states that some Providers may require EntryProcessors to be serializable, but it's not a requirement for most Providers.

I strongly believe that forcing this potential instability into the JCache specification by requiring EntryProcessors to extend Serializable, forcing every application developer to ensure correct serializability of their EntryProcessors (Lambda or not) and ensuring every Provider implements such semantics is a bad proposition. 

Importantly implementations *may* choose to offer this type of capability (which is naturally outside the specification at the moment as it's only designed for Java 6), say with customizable levels of "stability" or different approaches to ensure "stability" as they see fit.   Some implementations may choose not to provide this capability at all.

**Comment by dsetrakyan** [comment]
I see your point, but cannot say I completely agree. I don't think that being Java6-compatible in any way conflicts with being Java8-friendly. JCache does provide a way for EntryProcessor to be Serializable in Java8, after all, I even put an example for it above in this thread. However, it looks rather dirty (definitely not the code I would like to write). 

Thanks for you very thorough response on this.

-Dmitriy

**Comment by brianoliver** [comment]
I completely see your point as well.   On the surface it looks great but even after long discussions about the semantics with the Java Language Team (and reading most if not all of there discussions / design work), there's no great single perfect solution for the Java Platform, let alone the JCache specification.

Ultimately application developers need to choose how/if/when Lambda expressions are/should be serializable.   Assuming/making/forcing them all to be serializable is obviously wrong.  At the same time the alternative argument for ensuring they aren't serializable is arguably also wrong (though arguably much safer).   I think that's why the Java Team went with the "safe" option.   We followed the same (arguably safer) pattern.

Perhaps we can revisit this if/when we look at a JCache for Java 8+ update.  I'm guessing we'd add some kind of helper function/annotation to provide developers to specify if an expression is serializable.
