### ISSUE TITLE
Recent commit obliterates history in the Cache.java file

### ISSUE THREAD

**Issue by chrisdennis** [jsr107/jsr107spec#311]
I tried reporting this through a comment on the issue - but got no traction.  Commit a6fee0f403546b95aee83501d4e72194d5f8b3c9 completely obliterates the history of the Cache.java file.  I think there is a strong argument for a force push here to clean this up before any more commits get layered on top.  In a similar manner, could we move development of this async extension in to a branch (possibly of a developer fork) so that changes can be rebased and reworked to eventually prevent a logical sequence of commits.  For example it would seem sensible to squash a6fee0f403546b95aee83501d4e72194d5f8b3c9 and 89939cdee398e6c9155550db4b8c11c8dea6f7e5 together, since one is just a fix of mistakes made in the other.

**Comment by gregrluck** [comment]
Master contains development of 1.1.

We have been developing on master and tagging releases for the past couple of years. This is consistent. 

The change does not obliterate history. It makes it hard to compare code changes from c0fb8415e31ad2a5985d06f9b258332a94ed6409 to c0fb8415e31ad2a5985d06f9b258332a94ed6409 but it does not make it hard to compare any other versions.

Unfortunately the formatting changes applied in c0fb8415e31ad2a5985d06f9b258332a94ed6409 made it hard to work with the IDE.

Saying a "fix of mistakes" is pretty inflammatory. It actually resolves a todo on a return type question raised in December and then resolved in today's meeting. Making todos, thinking about stuff and resolving them is how we move forward. We created a bunch of todos today which we will resolve in the next week, and so on.
