### ISSUE TITLE
Managed lifecycle of CacheManager

### ISSUE THREAD

**Issue by snicoll** [jsr107/jsr107spec#316]
I want to make sure I got this right and I hope I used the right channel. Let me know otherwise and I'll move this issue.

I find the current API a bit confusing with regards to how the lifecycle of a `CacheManager` should be managed. Let's take the basic example of `Caching.getCachingProvider().getCacheManager()`. This call may return me a "new" `CacheManager` or an existing `CacheManager` that was created previously with the same "settings" (`ClassLoader` and `URI`).

`CacheManager` has a `close` method with no specific Javadoc details as how/when it should be invoked but my general understanding is that it should be invoked when the "component"/"app" terminates to reclaim resources or clean stuff up. 

Here is the problem. How do I know that the `CacheManager` I hold belongs to me? Maybe it was provided by the environment in some form. Maybe it's shared. 

I am not sure this is clear so I want to describe this in a different way.

* I have a method to retrieve a ` CacheManager`
* This `CacheManager` has a `close` method that I should invoke when "I am done with it"
* I have no idea when I invoke said method if I am managing the returned `CacheManager` or if a component that has called the method previously owns it.

So, yes, calling `close` multiple times works per spec but my main problem is that when one component terminates and not the others. This is definitely in the corner case area but I want to make sure I didn't overlook something from the spec.

I am not sure if the idea of a _managed_ `CacheManager` provided by the environment and shared by multiple apps make sense but that would be yet another example of this problem.

Thoughts?

**Comment by cruftex** [comment]
You cannot. Calling CacheManager.close() on the default cache manager on component level is the problem.

What you can do on component level:
- Use distinct caches with in the default cache manager and close them separately
- Use a unique cache manager by retrieving with distinct URI and/or classpath.
 
I would say, closing the default cache manager only makes sense during application shutdown or in general the default manager lifecycle is tied to the application lifecycle.

**Comment by snicoll** [comment]
Thanks for the reply. So a `CacheManager` is not shared by multiple applications. Never. 

In a provisioned environment, this can happen (even a bit uncommon). For instance a `DataSource` retrieved via JNDI.

**Comment by cruftex** [comment]
> Thanks for the reply. So a CacheManager is not shared by multiple applications. Never.

Oops. That is an interesting point! I would say it depends on the caching implementation and whether the cache implementation is loaded by the container or application class loader.

The reference implementation RICachingProvider defines:

  public ClassLoader getDefaultClassLoader() {
    return getClass().getClassLoader();
  }

I checked the current implementations github repositories:

Infinispan: dito

EHCache: dito

Hazelcast: dito

I thought there are more variants on this. Maybe it could be instead:

  public ClassLoader getDefaultClassLoader() {
    return Thread.currentThread().getContextClassLoader();
  }

This means, in short: Within an application container context, an application only gets a distinct cache manager, when it comes with its own caching provider. This holds for the current implementations, at this moment. I am not sure whether it has to be this way by definition. The TCK needs to be checked on this. Will do it later.

Disclaimer: I am feeling not as classloader and application container expert, so a second thought on this would be nice...

**Comment by cruftex** [comment]
I did some experiments with getDefaultClassLoader variants and cannot find a TCK test that imposes any restrictions here.

=>
What you get when requesting the default cache manager in containerized applications depends on the cache implementation. There is nothing enforced by the standard.

**Comment by gregrluck** [comment]
To your original question:

The spec originally said in the CacheManager section:

*After closing a CacheManager, another instance, possibly representing the previously managed Caches, may be acquired using the CachingProvider that originally produced the CacheManager. This is covered in the section on CachingProviders.*

To clarify this I added:

*Closing a CacheManager does not necessarily destroy the contents of a CacheManager. It simply signals that the owning CacheManager is no longer required by the application and that future uses of that specific CacheManager instance should not be permitted. Depending on the implementation and Cache topology, e.g., a storage-backed or distributed caches, the contents of a closed CacheManager.*

To make this a little more concrete:
In Hazelcast and Coherence, a CacheManager exists in a running cluster. When you call CachingProvider.getCachingManager it will connect your application to that cluster. When you call close() it disconnects you from that cluster. The life cycle of the distributed cache is tied to the life cycle of the cluster.

In Ehcache in-process, i.e. not the distributed kind backed by Terracotta Server Array (at least when I was still at Terracotta and this is a little simplified) a CacheManager is typically described in configuration. When you close a CacheManager all of its contents will be discarded, unless caches are marked persistent. But the CacheManager itself exists in a config file. So when you get it again from the CachingProvider a new one will be created. If none of the caches were persistent you get new empty caches. However if they were persistent the new CacheManager will get created with populated caches.

Hope this helps.

**Comment by snicoll** [comment]
It does, thanks.

**Comment by cruftex** [comment]
The specification document 1.0 page 38 says:

> Closing a Cache does not necessarily destroy the contents of a Cache. It simply signals to the owning
> CacheManager that the Cache is no longer required by the application and that future uses of a
> specific Cache instance should not be permitted. Depending on the implementation and Cache
> topology, e.g., a storage-backed or distributed caches, the contents of a closed Cache may still be
> available and accessible by other applications or in fact via the Cache Manager that previously owned
> the Cache if an application calls getCache at some point in the future.

I checked the wordings of `CacheManager.close()` and `Cache.close()`. Adding this or the the last sentence to the Java Doc helps to avoid confusion.
