### ISSUE TITLE
Describe effects on loader and writer in Javadoc 

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107spec#317]
Follow-up from: https://github.com/jsr107/jsr107spec/issues/303

The effects on loaders and writer are sometime counter intuitive. The method containsKey() queries the cache state and does not invoke a loader. This might be obvious, however, some methods change their semantics depending on the configuration like get() and put(), some do not.

This is a pitfall for the API user. We should add explicit statements about this in the method Javadoc.

**Comment by brianoliver** [comment]
I agree that the javadoc and specification should be improved to clarify when CacheLoaders / CacheWriters are consulted.

**Comment by gregrluck** [comment]
We actually did a thorough job of describing when and if a loader or write is called in the spec. See Read-Through Caching and Write-Through Caching. I do agree with Brian that having it in the JavaDoc is a good idea. Am copying it now to each method.

**Comment by gregrluck** [comment]
Added JavaDoc for CacheLoader to:
*containsKey

**Comment by gregrluck** [comment]
The CacheWriter spec link is: https://docs.google.com/document/d/14BvLUyv5U3zhsbIGwA4hkLfFieBkaCPfaHazh_yQGSY/edit#heading=h.flkpf7mbzbsy
