### ISSUE TITLE
Factor out data access interface to avoid misuse and pitfalls

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107spec#318]
Follow-up on https://github.com/jsr107/jsr107spec/issues/303:

Motivation:

The cache interface is broad and addresses various aspects of a Caching API: data access, management, debugging, logging, introspection, accessing the cache state for performance reasons.

A part of the API is designed for data access and to be transparent about the cache existence. E.g. get(), behaves differently if the cache is configured for read-through.

Some methods do only address the cache state explicitly. That may lead to wrong code. For example the cache can be seen as a key/value store and/or as an interface to a key/value store. To find out whether there is already data for a specific key the code could do:

    if (cache.containsKey(key)) {
      ....
    }

That would be the best way, if there is only the cache. If the cache is operated in read-through, this is wrong. With the current set of defined methods, it has to be:

    if (cache.get(key) != null) {
      ....
    }

If the application should be CacheLoader agnostic, it has to be the latter.

So, using the cache methods correctly when read-through and/or write-through is enabled is potentially error prone. A natural request would be to make containsKey() also transparent and invoke the loader, if needed, does not make the situation any better, since the methods that solely address the cache state are also needed. See discussion on this in: https://github.com/jsr107/jsr107spec/issues/303

The cache methods, as a whole, may have 9 different variations of semantics:

- No loader/writer
- Loader
- Writer
- Loader and read through enabled
- Writer and write through enabled
- Loader & Writer
- Loader & Writer, read through enabled
- Loader & Writer, write through enabled
- Loader & Writer, read/write through enabled

Code review is difficult. Using cache.containsKey() can be correct now, but may be incorrect tomorrow, since somebody configured in a loader.

To mitigate the problem, the methods that are available now and act transparently could be extracted:

     class TransparentKeyValueAccess {
        V get(K);
        Map<K,V> getAll(Set<K>);
        void put(K, T);
        ...
     }

And then: 

     Cache extends TransparentKeyValueAccess

For pure data access, the usage of the thinner interface should be endorsed. Using the rich cache interface would mean: Here we need to interact with the cache state.

There are more possible solutions to this, but I like to evolve the API in an iterative way. So, this would be a feasible next (tiny) step.

**Comment by cruftex** [comment]
Little show stopper:

    boolean cache.remove(key)

exposes the cache state and is therefore not transparently usable. Overriding and adding a return type is not possible. Options:

1. Have an interface contract in TransparentKeyValueAccess that says the return value has to be igored.
2. Work with cache.put(key, null) and leave out remove()

**Comment by brianoliver** [comment]
Have you considered using EntryProcessors for the operations/semantics you require?

Introducing a new super interface may seem a little heavy handed?

**Comment by cruftex** [comment]
> Have you considered using EntryProcessors for the operations/semantics you require?

This request is not about adding semantics, it is about adding a targeted interface for existing semantics.

Maybe my motivation text was to long?

The basic idea is to fulfill Alex' idea in #303 that the Cache should be a transparent interface to an SoR. It is a transparent interface, but only if the correct methods are used!

> Introducing a new super interface may seem a little heavy handed?

The purposed super interface contains only methods that are yet present in the Cache interface. That is the only compatible way to achieve this in terms of API evolution.

This can be done in a maintenance release without breaking existing implementations.

**Comment by cruftex** [comment]
Closing this, maybe something for 2.0
