### ISSUE TITLE
CompletionListenerFuture wakeup for multiple threads, protect against spurious wakeup

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107spec#320]
From CompletionListenerFuture:

    public void onCompletion() throws IllegalStateException {
      synchronized (this) {
        if (isCompleted) {
          throw new IllegalStateException("Attempted to use a CompletionListenerFuture instance more than once");
        } else {
          isCompleted = true;
          notify();
        }
      }
    }

This is notifying only one thread upon completion, all others block indefinitely.

Solution: notify() -> notifyAll()

From: https://github.com/jsr107/jsr107spec/issues/348

The following code fails to deal with spurious wakeup. It is allowed that the thread is notified without a reason. To deal with this situation, the if(!completed) should be while(!completed). Of course the remaining timeout needs to be corrected.

```
 @Override
  public Void get(long timeout, TimeUnit unit) throws InterruptedException, ExecutionException, TimeoutException {
    synchronized (this) {
      if (!isCompleted) {
        unit.timedWait(this, timeout);
      }

      if (isCompleted) {
        if (exception == null) {
          return null;
        } else {
          throw new ExecutionException(exception);
        }
      } else {
        throw new TimeoutException();
      }
    }
  }
```

**Comment by pveentjer** [comment]
👍 it should indeed be notifyAll.

**Comment by cruftex** [comment]
There are three findings in the `CompletionListenerFuture` at the moment. Additional ones:

https://github.com/jsr107/jsr107spec/issues/348
https://github.com/jsr107/jsr107spec/issues/346

Will probably bundle this.

**Comment by cruftex** [comment]
Pull request is ready. 

Another Pull Request against the TCK is extending the tests to better check the current behavior so we don't introduce an regression. A test for the bug is also included but optional. See PR comment.

**Comment by cruftex** [comment]
The PR on the CompletionListenerFuture also does minor corrections in the JavaDoc, since the existing one was stating that a value is returned.

**Comment by gregrluck** [comment]
Closed with PR 371
