### ISSUE TITLE
TCK statistic checks for EntryPorcessor and Iterator check for read count, but value is not read

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107spec#321]
This applies to the following TCK methods in  org.jsr107.tck.management.CacheMBStatisticsBeanTest:

* testCacheStatisticsInvokeEntryProcessorRemove
* testCacheStatisticsInvokeEntryProcessorUpdate 
* testCacheStatisticsInvokeEntryProcessorGet
* testCacheStatisticsInvokeEntryProcessorNoOp
* testIterateAndRemove

These methods check whether a miss, hit or get  is counted, but the data is not read via Entry.getValue().

With this requirement the statistic counters will not show relevant information as soon as Iterator or the EntryProcessor is used.

To put it more formal, the statement

    boolean present = cache.containsKey(key);

and the statement

    boolean present = invoke(key, new EntryProcessor<K, V, Boolean>() {
      @Override
      public Boolean process(MutableEntry<K, V> entry, Object... arguments) {
        return entry.exists();
      }
    });

should have identical semantics. It should be possible to augment any other cache operation via invoke() / invokeAll()

For the Iterator it makes sense that the value is always accessed, since a user of the Iterator interface will imply that the iterated entries always satisfy: Entry.getValue() != null.

For the EntryProcessor this is not the case, Entry.getValue() aka MutableEntry.getValue() may return null.

IMHO, the best possible enhancement would be:

- TCK checks that hit, get and miss counter is not updated when EntryProcessor user is not requesting the value
- TCK checks on iterator statistics stay the same
- Addition to interface contract Entry.getValue(): always returns a non-null value
- Addition to interface contract MutableEntry.getValue(): Overridden contract, may return null value

**Comment by brianoliver** [comment]
As this is a TCK issue, I'll close it here.  The new issue in the TCK is: https://github.com/jsr107/jsr107tck/issues/81
