### ISSUE TITLE
Please change all pom.xml versions to 1.1-SNAPSHOT

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107spec#324]
Currently all projects have a fixed version (Spec, TCK, RI).

The Spec pom.xml says it is 1.1, but 1.1 is unreleased yet.

The TCK pom.xml says it is 1.0.1. This reflects the current repository state, but as soon as changes are commited, this gets wrong.

Please change all pom.xml versions to 1.1-SNAPSHOT.

**Comment by brianoliver** [comment]
Change the spec to be 1.0.1-SNAPSHOT in preparation for release 1.0.1.
