### ISSUE TITLE
javax.cache.configuration is not exported in manifest (OSGi issue)

### ISSUE THREAD

**Issue by exmortal** [jsr107/jsr107spec#326]
Hi there.

It seems that cache-api can't be used in OSGi environment since javax.cache.event is not available in export-package. I checked bnd.bnd file and didn't find javax.cache.event package there. 
Is it a bug or maybe I use cache-api in a wrong way ?

Thanks,
Vlad

**Comment by keilw** [comment]
Actually looking at https://github.com/jsr107/jsr107spec/issues/327 it may be unintended luck, it is not exposing OSGi bundle information in the manifest. Since OSGi would pretty likely interpret the "PFD" postfix as NEWER than the actual 1.0.0 release, too.,

**Comment by exmortal** [comment]
I know that this issue can be defeated via workaround mentioned before, but I believe that this is a bug cause javax.cache.event and javax.cache.configuration are major packages and they should be exported in order to use in a proper OSGi way

Original bnd.bnd file contains only the following:
Export-Package: javax.cache;\
        javax.cache.annotation;\
        javax.cache.event;\
        javax.cache.spi;\
Bundle-SymbolicName: javax.cache
Bundle-Version: ${project.version}
 
javax.cache.event and javax.cache.configuration are missing. 
Simple update to bnd.bnd file can fix issue.

**Comment by keilw** [comment]
I am absolutely with you. Pivotal won't do this any more, they even dropped Gradle, so every responsible project has to do  this. JSR 354 is fully OSGi enabled, so is JSR 363 ;-)

**Comment by gregrluck** [comment]
Neither Brian nor I use OSGi and we have nothing in the build to verify anything with it so problems like this happen. 

Looking at the bnd.bnd I have added all the missing spec packages in. So we now have:

Export-Package: javax.cache;\
	javax.cache.annotation;\
	javax.cache.configuration;\
	javax.cache.event;\
	javax.cache.expiry;\
	javax.cache.integration;\
	javax.cache.management;\
	javax.cache.processor;\
	javax.cache.spi;\
Bundle-SymbolicName: javax.cache
Bundle-Version: ${project.version}

**Comment by keilw** [comment]
There is of course a license issue with the API that will likely cause Eclipse to not allow it, but still good to have OSGi working anyway.

**Comment by gregrluck** [comment]
What issue is that?

Regards

Greg Luck

web: http://gregluck.com <http://gregluck.com/>
skype: gregrluck
yahoo: gregrluck
mobile: +61 408 061 622

**Comment by keilw** [comment]
The Spec License;-)

**Comment by gregrluck** [comment]
Just looking at OSGi again, I see that we have packageinfo. Those currently say 1.0. 

# Declares the OSGi version of the package
version 1.0

I guess we should update those as well. Keeping track and incrementing for each change in the package seems tedious. What about:

a) delete packageinfo
b) change it to pick up the pom version.

**Comment by keilw** [comment]
For license issues, see the comment on https://github.com/jsr107/jsr107spec/issues/304.

**Comment by gregrluck** [comment]
Running some tests, our current config is ignoring the packageinfo files anyway. So going with the strategy of versioning each package to the same as the project. Deleted packageinfo files.

**Comment by ljacomet** [comment]
Did a quick test with the latest snapshot as part of [Ehcache 3 OSGi integration testing](https://github.com/ehcache/ehcache3/blob/master/osgi-test/src/test/java/org/ehcache/osgi/Jsr107OsgiTest.java), and I can confirm that configuration is now properly exported. Although, let's be honest, the test itself is minimal.
