### ISSUE TITLE
Maven version flaw in 1.0.0-PFD

### ISSUE THREAD

**Issue by keilw** [jsr107/jsr107spec#327]
Apparently the naming of "1.0.0-PFD" caused Maven to mistake it for the Latest release, see
http://search.maven.org/#search%7Cga%7C1%7Cjavax.cache

Therefore it could happen that Maven or other dependency systems based on it (Gradle, OSGi/Tycho) mistakenly use the PFD rather than Final artifact. Hopefully this may be resolved after 1.0.1, just try to watch out for misleading postfixes in future;-)

**Comment by gregrluck** [comment]
As noted this issue will be fixed by releasing 1.0.1.

**Comment by keilw** [comment]
Ok, as long as you don't forget it, but if 1.0.1 or 1.1 or whatever it'll end up needs EC review, I will do that anyway;-)

**Comment by gregrluck** [comment]
1.0.1 as a maintenance release needs EC review. Not sure how else to fix this issue.
