### ISSUE TITLE
Readme has dead links to Jenkins; Where is JavaDoc API online?

### ISSUE THREAD

**Issue by awhitford** [jsr107/jsr107spec#330]
The ReadMe file has a link to the JavaDoc here:  https://jsr107.ci.cloudbees.com/job/jsr107api/ws/target/apidocs/index.html

Alas, the *Jenkins instance is Hibernated*.  Where might we find the JavaDoc API?

And can those links to Jenkins be revised (or Jenkins reactivated)?

**Comment by fedy2** [comment]
Any news on this issue?

**Comment by ben-manes** [comment]
I'd just use javadoc.io, e.g. [cache-api:1.0.0](http://www.javadoc.io/doc/javax.cache/cache-api/1.0.0)

**Comment by gregrluck** [comment]
javadoc.io seems as good a place as any to point people to. We are not using CloudBees any longer.

**Comment by gregrluck** [comment]
Changed the readme to point to javadoc.io
