### ISSUE TITLE
How to declare expiry policy in annotation usage

### ISSUE THREAD

**Issue by rahmanusta** [jsr107/jsr107spec#332]
Is there any way to declare cache expiry policy while using JCache annotations?

**Comment by cruftex** [comment]
Hi Rahman,

unfortunately this isn't part of the JCache spec.

To do it in a standard compatible way, applications need to use the `CompleteConfiguration` class for this.

**Comment by gregrluck** [comment]
An class annotated with JCache annotations is an idiom for using an existing cache,not a way to configure one. 

There are two ways to configure caches:
1. Programmatically - JCache provides this for configuration options it cares about
2. Declaratively - this is the responsibility of the implementation

**Comment by rahmanusta** [comment]
I think it could be in spec.
