### ISSUE TITLE
Update compatible implementations

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107spec#344]
Compatible implementations should be updated. The "official" list is here:
https://jcp.org/aboutJava/communityprocess/implementations/jsr107/index.html

Alternatively we could transfer the https://github.com/cruftex/jsr107-test-zoo to jsr107 and link there.

**Comment by brianoliver** [comment]
I agree that we should update the compatible implementations, but it’s not the responsibility of the JCache Maintainers to test each and every implementation of JCache.

We simply can’t move the JSR-107-Test-Zoo into the JSR-107 TCK.

**Comment by cruftex** [comment]
> We simply can’t move the JSR-107-Test-Zoo into the JSR-107 TCK.

Of course not!

What I meant was:

I would be okay to move the current jsr107-test-zoo project under the "jsr107" GitHub organization. This way it can collaboratively maintained under the jsr107 hood. Anyhow, this was just an idea. I am open for anything that moves things forward.

**Comment by gregrluck** [comment]
I am Ok to move it as a new module under the JSR107 org. Jens is prepared to change the copyright to Oracle and the license to Apache. Seems to keep everything in one place.

**Comment by cruftex** [comment]
List of currently compatible versions:
https://github.com/cruftex/jsr107-test-zoo/blob/master/report.md

**Comment by cruftex** [comment]
Assigning to me. Next step would be the transfer of the test-zoo.

**Comment by gregrluck** [comment]
Even if it is moved to the JSR107 project, the JCP still insists on editing the official list. https://jcp.org/aboutJava/communityprocess/implementations/jsr107/index.html. All we can do is email them when a new one comes along.
