### ISSUE TITLE
ExpiryPolicy exception handling should not mandate error hiding

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107spec#354]
The JavaDoc on `ExpiryPolicy.getExpiryForCreation()` says:

> Should an exception occur while determining the Duration, an implementation
> specific default {@link Duration} will be used.

There is no TCK test for it.

What the Spec demands is, that exceptions are swallowed.  That is not a good idea.
https://en.wikipedia.org/wiki/Error_hiding

Suggestion:

Remove the sentence. Each implementation should be able to handle this in the best way.

**Comment by gregrluck** [comment]
All implementations have default durations. e.g. Ehcache was 30 minutes. So it should be a simple thing for an implementation to return a default if something goes wrong. We are essentially saying that each implementation has a constant which is used if nothing else gets calculated. 

I agree with you about not swallowing exceptions. But this is a simple default configuration issue.

Note this could happen if an implementation has an invalid config. It should fail fast and be reporting the issue. 

So not fixing this one.
