### ISSUE TITLE
CacheLoader and CacheWriter Implementation

### ISSUE THREAD

**Issue by Kamal15** [jsr107/jsr107spec#367]
Why default / disk persistence implementation for CacheLoader and CacheWriter is not provided ? 

The custom implementations using MapDB / RocksDB leads to third-party dependencies and it might be error-prone.

**Comment by cruftex** [comment]
Thanks for reaching out.

The issue tracker is for coordinating work on how we can improve the JCache standard. While your questions are relevant, they need some broader discussion and feedback, before becoming something that we can actually do. Furthermore, the standard is finalized. At this point we can improve the documentation and fix inconsistencies.

If you put these questions on StackOverflow you will reach a broader audience then here. That is good for having a good discussion and helps the JCache standard as well. Actually the above are two different topics: "Specification vs. Implementation", "Persistence and CacheLoader and CacheWriter"

Closing. Looking forward for questions on StackOverflow. Cheers!
