### ISSUE TITLE
JCache API does not compile with JDK 8

### ISSUE THREAD

**Issue by jerrinot** [jsr107/jsr107spec#376]
JDK 8 has a strict(-er) JavaDoc validation. It does not compile the [current master](b057292c45a1a1d6fa438e01c948bd61962eb524)

There is a bunch of warning and this error:
```
/home/jara/devel/oss/jsr107spec/src/main/java/javax/cache/processor/MutableEntry.java:53: error: self-closing element not allowed
   * <p/>
     ^
/home/jara/devel/oss/jsr107spec/src/main/java/javax/cache/processor/MutableEntry.java:24: error: self-closing element not allowed
 * <p/>
```

**Comment by cruftex** [comment]
Fixed the two errors, so it compiles.

There is still a bunch of warnings complaining about missing documentation for the return value, for example:

> [WARNING] /home/jeans/tmp/jsr107/jsr107spec/src/main/java/javax/cache/annotation/CacheResult.java:132: warning: no @return
> [WARNING] @Nonbinding boolean skipGet() default false;
