### ISSUE TITLE
Publish new Release for MR 1

### ISSUE THREAD

**Issue by keilw** [jsr107/jsr107spec#394]
As the MR 1 Ballot succeeded, please tag a new 1.1 Release here.

**Comment by vbekiaris** [comment]
The final 1.1.0 artifact is [now available on maven central](http://search.maven.org/#artifactdetails%7Cjavax.cache%7Ccache-api%7C1.1.0%7Cjar) and has been [tagged here](https://github.com/jsr107/jsr107spec/tree/v1.1.0). This issue can now be closed.

**Comment by keilw** [comment]
It seems the tags are there, just noticed something very strange in the dependency chain, but that's for another ticket.
