### ISSUE TITLE
Change version number to 1.1.0

### ISSUE THREAD

**Issue by keilw** [jsr107/jsr107spec#395]
The [POM](https://github.com/jsr107/jsr107spec/blob/master/pom.xml) states version `1.1.0-SNAPSHOT`, but following the succesful MR 1 ballot, is there still a reason to remain in snapshot?

**Comment by gregrluck** [comment]
We need to release. So give me a chance

Regards

Greg Luck

web: http://gregluck.com <http://gregluck.com/>
skype: gregrluck
mobile US: +1 650 924 6244
mobile Australia: +61 408 061 622

**Comment by vbekiaris** [comment]
Fixed by https://github.com/jsr107/jsr107spec/commit/692be1cf72cb5f9ac3d9fc62aa463c96711617da

Also `1.1.0` artifacts for specification and RI modules are now available on maven central. This issue can be now closed.

**Comment by keilw** [comment]
That seems to work but why this ancient CDI version? Was it because there is still JDK 6 compabitility after all these years?
